// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

import { c, RPC, RPCStream, RPCRequestStream } from 'hrpc/runtime'
import { getEncoding } from './messages.js'

const methods = new Map([
  ['@pearschool-mini/rooms', 0],
  [0, '@pearschool-mini/rooms'],
  ['@pearschool-mini/add-room', 1],
  [1, '@pearschool-mini/add-room'],
  ['@pearschool-mini/join-room', 2],
  [2, '@pearschool-mini/join-room'],
  ['@pearschool-mini/messages', 3],
  [3, '@pearschool-mini/messages'],
  ['@pearschool-mini/add-message', 4],
  [4, '@pearschool-mini/add-message'],
  ['@pearschool-mini/drives', 5],
  [5, '@pearschool-mini/drives'],
  ['@pearschool-mini/add-file', 6],
  [6, '@pearschool-mini/add-file'],
  ['@pearschool-mini/tasks', 7],
  [7, '@pearschool-mini/tasks'],
  ['@pearschool-mini/add-task', 8],
  [8, '@pearschool-mini/add-task'],
  ['@pearschool-mini/delete-task', 9],
  [9, '@pearschool-mini/delete-task'],
  ['@pearschool-mini/courses', 10],
  [10, '@pearschool-mini/courses'],
  ['@pearschool-mini/add-course', 11],
  [11, '@pearschool-mini/add-course'],
  ['@pearschool-mini/delete-course', 12],
  [12, '@pearschool-mini/delete-course'],
  ['@pearschool-mini/videos', 13],
  [13, '@pearschool-mini/videos'],
  ['@pearschool-mini/add-video', 14],
  [14, '@pearschool-mini/add-video'],
  ['@pearschool-mini/account-invite', 15],
  [15, '@pearschool-mini/account-invite'],
  ['@pearschool-mini/set-blind-peer-key', 16],
  [16, '@pearschool-mini/set-blind-peer-key']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@pearschool-mini/rooms', getEncoding('@pearschool-mini/rooms')],
      ['@pearschool-mini/add-room', c.string],
      ['@pearschool-mini/join-room', c.string],
      ['@pearschool-mini/messages', getEncoding('@pearschool-mini/get-messages')],
      ['@pearschool-mini/add-message', getEncoding('@pearschool-mini/add-message')],
      ['@pearschool-mini/drives', getEncoding('@pearschool-mini/drives')],
      ['@pearschool-mini/add-file', getEncoding('@pearschool-mini/file')],
      ['@pearschool-mini/tasks', getEncoding('@pearschool-mini/tasks')],
      ['@pearschool-mini/add-task', getEncoding('@pearschool-mini/task')],
      ['@pearschool-mini/delete-task', getEncoding('@pearschool-mini/delete-task')],
      ['@pearschool-mini/courses', getEncoding('@pearschool-mini/courses')],
      ['@pearschool-mini/add-course', getEncoding('@pearschool-mini/course')],
      ['@pearschool-mini/delete-course', getEncoding('@pearschool-mini/delete-course')],
      ['@pearschool-mini/videos', getEncoding('@pearschool-mini/videos')],
      ['@pearschool-mini/add-video', c.string],
      ['@pearschool-mini/account-invite', c.string],
      ['@pearschool-mini/set-blind-peer-key', c.string]
    ])
    this._responseEncodings = new Map([
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  rooms(args) {
    return this._callSync('@pearschool-mini/rooms', args)
  }

  addRoom(args) {
    return this._callSync('@pearschool-mini/add-room', args)
  }

  joinRoom(args) {
    return this._callSync('@pearschool-mini/join-room', args)
  }

  messages(args) {
    return this._callSync('@pearschool-mini/messages', args)
  }

  addMessage(args) {
    return this._callSync('@pearschool-mini/add-message', args)
  }

  drives(args) {
    return this._callSync('@pearschool-mini/drives', args)
  }

  addFile(args) {
    return this._callSync('@pearschool-mini/add-file', args)
  }

  tasks(args) {
    return this._callSync('@pearschool-mini/tasks', args)
  }

  addTask(args) {
    return this._callSync('@pearschool-mini/add-task', args)
  }

  deleteTask(args) {
    return this._callSync('@pearschool-mini/delete-task', args)
  }

  courses(args) {
    return this._callSync('@pearschool-mini/courses', args)
  }

  addCourse(args) {
    return this._callSync('@pearschool-mini/add-course', args)
  }

  deleteCourse(args) {
    return this._callSync('@pearschool-mini/delete-course', args)
  }

  videos(args) {
    return this._callSync('@pearschool-mini/videos', args)
  }

  addVideo(args) {
    return this._callSync('@pearschool-mini/add-video', args)
  }

  accountInvite(args) {
    return this._callSync('@pearschool-mini/account-invite', args)
  }

  setBlindPeerKey(args) {
    return this._callSync('@pearschool-mini/set-blind-peer-key', args)
  }

  onRooms(responseFn) {
    this._handlers['@pearschool-mini/rooms'] = responseFn
  }

  onAddRoom(responseFn) {
    this._handlers['@pearschool-mini/add-room'] = responseFn
  }

  onJoinRoom(responseFn) {
    this._handlers['@pearschool-mini/join-room'] = responseFn
  }

  onMessages(responseFn) {
    this._handlers['@pearschool-mini/messages'] = responseFn
  }

  onAddMessage(responseFn) {
    this._handlers['@pearschool-mini/add-message'] = responseFn
  }

  onDrives(responseFn) {
    this._handlers['@pearschool-mini/drives'] = responseFn
  }

  onAddFile(responseFn) {
    this._handlers['@pearschool-mini/add-file'] = responseFn
  }

  onTasks(responseFn) {
    this._handlers['@pearschool-mini/tasks'] = responseFn
  }

  onAddTask(responseFn) {
    this._handlers['@pearschool-mini/add-task'] = responseFn
  }

  onDeleteTask(responseFn) {
    this._handlers['@pearschool-mini/delete-task'] = responseFn
  }

  onCourses(responseFn) {
    this._handlers['@pearschool-mini/courses'] = responseFn
  }

  onAddCourse(responseFn) {
    this._handlers['@pearschool-mini/add-course'] = responseFn
  }

  onDeleteCourse(responseFn) {
    this._handlers['@pearschool-mini/delete-course'] = responseFn
  }

  onVideos(responseFn) {
    this._handlers['@pearschool-mini/videos'] = responseFn
  }

  onAddVideo(responseFn) {
    this._handlers['@pearschool-mini/add-video'] = responseFn
  }

  onAccountInvite(responseFn) {
    this._handlers['@pearschool-mini/account-invite'] = responseFn
  }

  onSetBlindPeerKey(responseFn) {
    this._handlers['@pearschool-mini/set-blind-peer-key'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@pearschool-mini/rooms',
      '@pearschool-mini/add-room',
      '@pearschool-mini/join-room',
      '@pearschool-mini/messages',
      '@pearschool-mini/add-message',
      '@pearschool-mini/drives',
      '@pearschool-mini/add-file',
      '@pearschool-mini/tasks',
      '@pearschool-mini/add-task',
      '@pearschool-mini/delete-task',
      '@pearschool-mini/courses',
      '@pearschool-mini/add-course',
      '@pearschool-mini/delete-course',
      '@pearschool-mini/videos',
      '@pearschool-mini/add-video',
      '@pearschool-mini/account-invite',
      '@pearschool-mini/set-blind-peer-key'
    ].includes(command)
  }
}

export default HRPC
