// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

import { c, b4a, assert, DispatchError, ERRORS } from 'hyperdispatch/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null
    this._handler8 = null
    this._handler9 = null

    this._missing = 10
  }

  add (name, handler) {
    switch (name) {
      case '@pearschool-mini/add-writer':
        this._handler0 = handler
        break
      case '@pearschool-mini/add-invite':
        this._handler1 = handler
        break
      case '@pearschool-mini/add-room':
        this._handler2 = handler
        break
      case '@pearschool-mini/add-message':
        this._handler3 = handler
        break
      case '@pearschool-mini/add-drive':
        this._handler4 = handler
        break
      case '@pearschool-mini/add-task':
        this._handler5 = handler
        break
      case '@pearschool-mini/delete-task':
        this._handler6 = handler
        break
      case '@pearschool-mini/add-course':
        this._handler7 = handler
        break
      case '@pearschool-mini/delete-course':
        this._handler8 = handler
        break
      case '@pearschool-mini/add-video':
        this._handler9 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@pearschool-mini/add-writer"')
    assert(this._handler1 !== null, 'Missing handler for "@pearschool-mini/add-invite"')
    assert(this._handler2 !== null, 'Missing handler for "@pearschool-mini/add-room"')
    assert(this._handler3 !== null, 'Missing handler for "@pearschool-mini/add-message"')
    assert(this._handler4 !== null, 'Missing handler for "@pearschool-mini/add-drive"')
    assert(this._handler5 !== null, 'Missing handler for "@pearschool-mini/add-task"')
    assert(this._handler6 !== null, 'Missing handler for "@pearschool-mini/delete-task"')
    assert(this._handler7 !== null, 'Missing handler for "@pearschool-mini/add-course"')
    assert(this._handler8 !== null, 'Missing handler for "@pearschool-mini/delete-course"')
    assert(this._handler9 !== null, 'Missing handler for "@pearschool-mini/add-video"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      case 7:
        return this._handler7(op.value, context)
      case 8:
        return this._handler8(op.value, context)
      case 9:
        return this._handler9(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@pearschool-mini/add-writer',
  id: 0,
  enc: getEncoding('@pearschool-mini/writer')
}

const route1 = {
  name: '@pearschool-mini/add-invite',
  id: 1,
  enc: getEncoding('@pearschool-mini/invite')
}

const route2 = {
  name: '@pearschool-mini/add-room',
  id: 2,
  enc: getEncoding('@pearschool-mini/room')
}

const route3 = {
  name: '@pearschool-mini/add-message',
  id: 3,
  enc: getEncoding('@pearschool-mini/message')
}

const route4 = {
  name: '@pearschool-mini/add-drive',
  id: 4,
  enc: getEncoding('@pearschool-mini/drive')
}

const route5 = {
  name: '@pearschool-mini/add-task',
  id: 5,
  enc: getEncoding('@pearschool-mini/task')
}

const route6 = {
  name: '@pearschool-mini/delete-task',
  id: 6,
  enc: getEncoding('@pearschool-mini/delete-task')
}

const route7 = {
  name: '@pearschool-mini/add-course',
  id: 7,
  enc: getEncoding('@pearschool-mini/course')
}

const route8 = {
  name: '@pearschool-mini/delete-course',
  id: 8,
  enc: getEncoding('@pearschool-mini/delete-course')
}

const route9 = {
  name: '@pearschool-mini/add-video',
  id: 9,
  enc: getEncoding('@pearschool-mini/video')
}

function getRouteByName (name) {
  switch (name) {
    case '@pearschool-mini/add-writer':
      return route0
    case '@pearschool-mini/add-invite':
      return route1
    case '@pearschool-mini/add-room':
      return route2
    case '@pearschool-mini/add-message':
      return route3
    case '@pearschool-mini/add-drive':
      return route4
    case '@pearschool-mini/add-task':
      return route5
    case '@pearschool-mini/delete-task':
      return route6
    case '@pearschool-mini/add-course':
      return route7
    case '@pearschool-mini/delete-course':
      return route8
    case '@pearschool-mini/add-video':
      return route9
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    case 7:
      return route7
    case 8:
      return route8
    case 9:
      return route9
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

export {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
