// This file is autogenerated by the hyperschema compiler
// Schema Version: 6
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 6

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @pearschool-mini/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @pearschool-mini/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @pearschool-mini/room
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      invite: r2,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/rooms
const encoding3 = c.array(c.frame(encoding2))

// @pearschool-mini/message
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/messages
const encoding5 = c.array(c.frame(encoding4))

// @pearschool-mini/get-messages
const encoding6 = {
  preencode(state, m) {
    encoding5.preencode(state, m.messages)
    c.string.preencode(state, m.roomId)
  },
  encode(state, m) {
    encoding5.encode(state, m.messages)
    c.string.encode(state, m.roomId)
  },
  decode(state) {
    const r0 = encoding5.decode(state)
    const r1 = c.string.decode(state)

    return {
      messages: r0,
      roomId: r1
    }
  }
}

// @pearschool-mini/add-message
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    c.string.preencode(state, m.roomId)
  },
  encode(state, m) {
    c.string.encode(state, m.text)
    c.string.encode(state, m.roomId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      text: r0,
      roomId: r1
    }
  }
}

// @pearschool-mini/drive
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/drives
const encoding9 = c.array(c.frame(encoding8))

// @pearschool-mini/file
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.uri)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.name)
    c.string.encode(state, m.uri)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: r0,
      uri: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/task
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    state.end++ // max flag is 4 so always one byte

    if (version >= 2 && m.description) c.string.preencode(state, m.description)
    if (version >= 2 && m.dueDate) c.int.preencode(state, m.dueDate)
    c.string.preencode(state, m.status)
    if (version >= 2 && m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.description) ? 1 : 0) |
      ((version >= 2 && m.dueDate) ? 2 : 0) |
      ((version >= 2 && m.info) ? 4 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (version >= 2 && m.description) c.string.encode(state, m.description)
    if (version >= 2 && m.dueDate) c.int.encode(state, m.dueDate)
    c.string.encode(state, m.status)
    if (version >= 2 && m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      description: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      dueDate: (version >= 2 && (flags & 2) !== 0) ? c.int.decode(state) : 0,
      status: c.string.decode(state),
      info: (version >= 2 && (flags & 4) !== 0) ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/tasks
const encoding12 = c.array(c.frame(encoding11))

// @pearschool-mini/delete-task
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      id: r0
    }
  }
}

// @pearschool-mini/course
const encoding14 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.title)
    c.string.preencode(state, m.instructor)
    state.end++ // max flag is 8 so always one byte

    if (version >= 4 && m.room) c.string.preencode(state, m.room)
    if (version >= 4 && m.startDate) c.int.preencode(state, m.startDate)
    c.string.preencode(state, m.status)
    if (version >= 4 && m.info) c.json.preencode(state, m.info)
    if (version >= 5 && m.description) c.string.preencode(state, m.description)
  },
  encode(state, m) {
    const flags =
      ((version >= 4 && m.room) ? 1 : 0) |
      ((version >= 4 && m.startDate) ? 2 : 0) |
      ((version >= 4 && m.info) ? 4 : 0) |
      ((version >= 5 && m.description) ? 8 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.title)
    c.string.encode(state, m.instructor)
    c.uint.encode(state, flags)

    if (version >= 4 && m.room) c.string.encode(state, m.room)
    if (version >= 4 && m.startDate) c.int.encode(state, m.startDate)
    c.string.encode(state, m.status)
    if (version >= 4 && m.info) c.json.encode(state, m.info)
    if (version >= 5 && m.description) c.string.encode(state, m.description)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      title: r1,
      instructor: r2,
      room: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      startDate: (version >= 4 && (flags & 2) !== 0) ? c.int.decode(state) : 0,
      status: c.string.decode(state),
      info: (version >= 4 && (flags & 4) !== 0) ? c.json.decode(state) : null,
      description: (version >= 5 && (flags & 8) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @pearschool-mini/courses
const encoding15 = c.array(c.frame(encoding14))

// @pearschool-mini/delete-course
const encoding16 = encoding13

// @pearschool-mini/video
const encoding17 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.type)
    c.json.preencode(state, m.blob)
    state.end++ // max flag is 1 so always one byte

    if (version >= 6 && m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = (version >= 6 && m.info) ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.string.encode(state, m.type)
    c.json.encode(state, m.blob)
    c.uint.encode(state, flags)

    if (version >= 6 && m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.json.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      type: r2,
      blob: r3,
      info: (version >= 6 && (flags & 1) !== 0) ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/videos
const encoding18 = c.array(c.frame(encoding17))

// @pearschool-mini/invite/hyperdb#0
const encoding19 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @pearschool-mini/room/hyperdb#1
const encoding20 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.invite)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.name)
    c.string.encode(state, m.invite)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      invite: r2,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/message/hyperdb#2
const encoding21 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/drive/hyperdb#3
const encoding22 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      key: null,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/task/hyperdb#4
const encoding23 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    state.end++ // max flag is 4 so always one byte

    if (version >= 2 && m.description) c.string.preencode(state, m.description)
    if (version >= 2 && m.dueDate) c.int.preencode(state, m.dueDate)
    c.string.preencode(state, m.status)
    if (version >= 2 && m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.description) ? 1 : 0) |
      ((version >= 2 && m.dueDate) ? 2 : 0) |
      ((version >= 2 && m.info) ? 4 : 0)

    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (version >= 2 && m.description) c.string.encode(state, m.description)
    if (version >= 2 && m.dueDate) c.int.encode(state, m.dueDate)
    c.string.encode(state, m.status)
    if (version >= 2 && m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      description: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      dueDate: (version >= 2 && (flags & 2) !== 0) ? c.int.decode(state) : 0,
      status: c.string.decode(state),
      info: (version >= 2 && (flags & 4) !== 0) ? c.json.decode(state) : null
    }
  }
}

// @pearschool-mini/course/hyperdb#5
const encoding24 = {
  preencode(state, m) {
    c.string.preencode(state, m.title)
    c.string.preencode(state, m.instructor)
    state.end++ // max flag is 8 so always one byte

    if (version >= 4 && m.room) c.string.preencode(state, m.room)
    if (version >= 4 && m.startDate) c.int.preencode(state, m.startDate)
    c.string.preencode(state, m.status)
    if (version >= 4 && m.info) c.json.preencode(state, m.info)
    if (version >= 5 && m.description) c.string.preencode(state, m.description)
  },
  encode(state, m) {
    const flags =
      ((version >= 4 && m.room) ? 1 : 0) |
      ((version >= 4 && m.startDate) ? 2 : 0) |
      ((version >= 4 && m.info) ? 4 : 0) |
      ((version >= 5 && m.description) ? 8 : 0)

    c.string.encode(state, m.title)
    c.string.encode(state, m.instructor)
    c.uint.encode(state, flags)

    if (version >= 4 && m.room) c.string.encode(state, m.room)
    if (version >= 4 && m.startDate) c.int.encode(state, m.startDate)
    c.string.encode(state, m.status)
    if (version >= 4 && m.info) c.json.encode(state, m.info)
    if (version >= 5 && m.description) c.string.encode(state, m.description)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      title: r1,
      instructor: r2,
      room: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      startDate: (version >= 4 && (flags & 2) !== 0) ? c.int.decode(state) : 0,
      status: c.string.decode(state),
      info: (version >= 4 && (flags & 4) !== 0) ? c.json.decode(state) : null,
      description: (version >= 5 && (flags & 8) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @pearschool-mini/video/hyperdb#6
const encoding25 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.type)
    c.json.preencode(state, m.blob)
    state.end++ // max flag is 1 so always one byte

    if (version >= 6 && m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = (version >= 6 && m.info) ? 1 : 0

    c.string.encode(state, m.name)
    c.string.encode(state, m.type)
    c.json.encode(state, m.blob)
    c.uint.encode(state, flags)

    if (version >= 6 && m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.json.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      type: r2,
      blob: r3,
      info: (version >= 6 && (flags & 1) !== 0) ? c.json.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@pearschool-mini/writer':
      return encoding0
    case '@pearschool-mini/invite':
      return encoding1
    case '@pearschool-mini/room':
      return encoding2
    case '@pearschool-mini/rooms':
      return encoding3
    case '@pearschool-mini/message':
      return encoding4
    case '@pearschool-mini/messages':
      return encoding5
    case '@pearschool-mini/get-messages':
      return encoding6
    case '@pearschool-mini/add-message':
      return encoding7
    case '@pearschool-mini/drive':
      return encoding8
    case '@pearschool-mini/drives':
      return encoding9
    case '@pearschool-mini/file':
      return encoding10
    case '@pearschool-mini/task':
      return encoding11
    case '@pearschool-mini/tasks':
      return encoding12
    case '@pearschool-mini/delete-task':
      return encoding13
    case '@pearschool-mini/course':
      return encoding14
    case '@pearschool-mini/courses':
      return encoding15
    case '@pearschool-mini/delete-course':
      return encoding16
    case '@pearschool-mini/video':
      return encoding17
    case '@pearschool-mini/videos':
      return encoding18
    case '@pearschool-mini/invite/hyperdb#0':
      return encoding19
    case '@pearschool-mini/room/hyperdb#1':
      return encoding20
    case '@pearschool-mini/message/hyperdb#2':
      return encoding21
    case '@pearschool-mini/drive/hyperdb#3':
      return encoding22
    case '@pearschool-mini/task/hyperdb#4':
      return encoding23
    case '@pearschool-mini/course/hyperdb#5':
      return encoding24
    case '@pearschool-mini/video/hyperdb#6':
      return encoding25
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
